config/routes.rb
Komana::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :projects
  get "welcome/index"
  
  
  root "welcome#index"
  get "welcome/dashboard"
  get "portfolios/contact"
  

  resources :portfolios
 
  resources :conversations do
	post :reply
	post :trash
	post :untrash
    post :mark_as_unread
    post :mark_as_read
    delete :delete
  end
  
  #needed for the dashboard overview
  resources :tasks do
    collection do
	    get "search"
    end
	post :update_position
  end
  
  resources :lists do
		post "move_up"
		post "move_down"
  end
  

  resources :projects do
		post "add_user"
		post "remove_user"
	resources :lists do
		resources :tasks
	end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :mailbox, :conversation

  def create

    
    @user = User.where("email = ?",conversation_params(:recipients)).first
    if @user.present?
      recipient_emails = conversation_params(:recipients)
      recipients = User.where(email: recipient_emails).all

      conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation
  	  flash[:notice] = "Die Nachricht wurde erfolgreich gesendet."
	
      redirect_to conversations_path
    else
      flash[:error] = "Der Benutzer konnte nicht gefunden werden."
      redirect_to new_conversation_path
    end
  end
  

    def index
 	if params[:partial]
 		@partial = params[:partial]
 	 else
 		@partial = "conversations/inbox"
 	 end
 	 
    end
  
  def reply
	    current_conversation = Conversation.find(params[:conversation_id])
      current_user.reply_to_conversation(current_conversation, params[:body])
      redirect_to conversation_path(current_conversation)
      flash[:notice] = "Die Antwort wurde erfolgreich gesendet."

  end

  def trash
      current_conversation = Conversation.find(params[:conversation_id])
      current_user.trash(current_conversation)    

      redirect_to conversations_path
  end

  def untrash
      current_conversation = Conversation.find(params[:conversation_id])
      current_user.untrash(current_conversation) 
      redirect_to :conversations
    end
  
  def mark_as_unread
      current_conversation = Conversation.find(params[:conversation_id])
      current_conversation.mark_as_unread(current_user)
      redirect_to conversations_path
  end
  
  def mark_as_read
      current_conversation = Conversation.find(params[:conversation_id])
      current_conversation.mark_as_read(current_user)
      redirect_to conversations_path
  end
  
  def delete
      current_conversation = Conversation.find(params[:conversation_id])
      current_conversation.mark_as_deleted(current_user)
      redirect_to conversations_path(:partial => 'conversations/trash')
  end

  private

  def mailbox
     @mailbox ||= current_user.mailbox
  end

  def conversation
      @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
      fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
      fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
      params[key].instance_eval do
        case subkeys.size
        when 0 then self
        when 1 then self[subkeys.first]
        else subkeys.map{|k| self[k] }
        end
      end
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
  
  

end

app/views/conversations/_inbox.html.erb
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h3>Posteingang <small>(Gesamt: <%= current_user.mailbox.inbox.count %> | Ungelesen: <%= current_user.mailbox.inbox(:read => false).count(:id, :distinct => true).to_s %>)</small></h3></div>
    <div class="col-lg-2"></div>
  </div>
  
  <div class="row">
    <%= render "conversations/list_group" %>
    
  
   
    <div class="col-lg-10">
      
      <div class="table-responsive">
        <table class="table table-hover table-striped"> 
          <tr>
            <th></th>
            <th>Thema</th>
            <th></th>
            <th>Letzte Nachricht</th>
            <th>Themenstarter</th>
            <th><%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_conversation_path,  {:'title' => 'Neue Konversation beginnen', :class => 'text-weak'} %></th>           
            <th><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, {}, {:'data-toogle' => 'tooltip', :title => 'Ausgewählte in den Papierkorb verschieben', :class => 'text-weak'}%></th>
          </tr>
          <% current_user.mailbox.inbox.order('updated_at ASC').each do |conversation|%>
          <% @Originator = User.where(email: conversation.originator.email).first%>
          <% @last_sender = User.where(email: conversation.last_sender.email).first%>
          <tr>
            <td><% if conversation.is_unread?(current_user) %><%= link_to '<i class="fa fa-envelope"></i>'.html_safe, conversation_mark_as_read_path(conversation),  :method => :post, :id => conversation.id, :class => 'black-link' %><% else %><%= link_to '<i class="fa fa-envelope-o text-weak"></i>'.html_safe, conversation_mark_as_unread_path(conversation),  :method => :post, :id => conversation.id %><% end %></td>
            <td><%= link_to conversation.subject, conversation_path(conversation), :method => :get %></td>
            <td><%= image_tag avatar_url(@last_sender,50), :size => "50", :class => 'pull-right' %></td>
            <td><em class="text-weak"><strong> <%= @last_sender.firstname %> <%= @last_sender.lastname %></strong> schreibt:</em><br> <%=raw truncate(conversation.last_message.body, :length => 40,  :omission => "...")%></td>
            <td><%= @Originator.firstname %> <%= @Originator.lastname %></td>
            <td><%= link_to '<i class="fa fa-mail-reply"></i>'.html_safe, conversation_path(conversation), {:'data-toogle' => 'tooltip', :title => 'Antworten', :class => 'text-weak'}%></td>
            <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, conversation_trash_path(conversation), :method => :post, :'data-toogle' => 'tooltip', :title => 'In den Papierkorb verschieben', :class => 'text-weak'%></td>
          </tr>
          
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/conversations/_list_group.erb
 <div class="col-lg-2">
        <div class="list-group">
         <%= link_to '<i class="fa fa-inbox"></i> Posteingang'.html_safe, conversations_path, :class => 'list-group-item' %>
         <%= link_to '<i class="glyphicon glyphicon-send"></i> Postausgang'.html_safe, conversations_path(:partial => 'conversations/sent'), :class => 'list-group-item' %>
         <%= link_to '<i class="fa fa-trash-o"></i> Papierkorb'.html_safe, conversations_path(:partial => 'conversations/trash'), :class => 'list-group-item' %>
        </div>
</div>

app/views/conversations/_new_conversation_modal.html.erb
<div class="modal fade" id="new_conversation_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Neue Konversation starten</h4>
      </div>
      <div class="modal-body">
        <%= form_for :conversation, url: :conversations do |f| %>
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-user"></i></span>
          <%= f.email_field :recipients, :autofocus => true, :class=>'form-control', :placeholder => 'E-Mail' %>
        </div>
        <div class="input-group">
      
          <%= f.text_field :subject,:class=>'form-control', :placeholder => 'Thema' %>
        </div>
        <div class="input-group">
      
          <%= f.text_area :body,:class=>'form-control', :placeholder => 'Nachricht' %>
        </div>
        <%= f.submit "Absenden", :class=>'btn btn-primary'%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
        <button type="button" class="btn btn-primary">Absenden</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/conversations/_sent.html.erb
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h3>Postausgang <small>(Gesamt: <%= current_user.mailbox.sentbox.count %>)</small></h3></div>

    <div class="col-lg-2"></div>
  </div>
  
  <div class="row">
    <%= render "conversations/list_group" %>
    
    <div class="col-lg-10">
      
      <div class="table-responsive">
        <table class="table table-hover table-striped"> 
          <tr>
            <th>Thema</th>
            <th></th>
            <th>Letzte Nachricht</th>
            <th>Themenstarter</th>
            <th><%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_conversation_path,  {:'title' => 'Neue Konversation beginnen', :class => 'text-weak'} %></th>           
          </tr>
          <% current_user.mailbox.sentbox.order('updated_at ASC').each do |conversation|%>
          <% @Originator = User.where(email: conversation.originator.email).first%>
          <% @last_sender = User.where(email: conversation.last_sender.email).first%>
          <tr>
            <td><%= link_to conversation.subject, conversation_path(conversation), :method => :get %></td>
            <td><%= image_tag avatar_url(@last_sender,50), :size => "50", :class => 'pull-right' %></td>
            <td><em class="text-weak"><strong> <%= @last_sender.firstname %><%= @last_sender.lastname %></strong> schreibt:</em><br> <%=raw truncate(conversation.last_message.body, :length => 40,  :omission => "...")%></td>
            <td><%= @Originator.firstname %> <%= @Originator.lastname %></td>
            <td></td>
          </tr>
          
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/conversations/_trash.html.erb
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8"><h3>Gelöscht <small>(Gesamt: <%= current_user.mailbox.trash.count %> | Ungelesen: <%= current_user.mailbox.trash(:read => false).count(:id, :distinct => true).to_s %>)</small></h3></div>
    <div class="col-lg-2"></div>
  </div>
  
  <div class="row">
    <%= render "conversations/list_group" %>
    
  
   
    <div class="col-lg-10">
      
      <div class="table-responsive">
        <table class="table table-hover table-striped"> 
          <tr>
            <tr>
            <th>Thema</th>
            <th></th>
            <th>Letzte Nachricht</th>
            <th>Themenstarter</th>
            <th><%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_conversation_path, {:'data-toogle' => 'tooltip', :title => 'Neue Konversation beginnen', :class => 'text-weak'}%></th>
            <th><%= link_to '<i class="fa fa-undo"></i>'.html_safe, {}, {:'data-toogle' => 'tooltip', :title => 'Ausgewählte in den Posteingang verschieben', :class => 'text-weak'}%></th>
            <th><%= link_to '<i class="fa fa-trash-o text-danger"></i>'.html_safe, {}, {:'data-toogle' => 'tooltip', :title => 'Ausgewählte entgültig löschen', :class => 'text-weak'}%></th>
          </tr>
          <% current_user.mailbox.trash.order('updated_at ASC').each do |conversation|%>
          <% @Originator = User.where(email: conversation.originator.email).first%>
          <% @last_sender = User.where(email: conversation.last_sender.email).first%>
          <tr>
            <td><%= link_to conversation.subject, conversation_path(conversation), :method => :get %></td>
            <td><%= image_tag avatar_url(@last_sender,50), :size => "50", :class => 'pull-right' %></td>
            <td><em class="text-weak"><strong> <%= @last_sender.firstname %> <%= @last_sender.lastname %></strong> schreibt:</em><br> <%=raw truncate(conversation.last_message.body, :length => 40,  :omission => "...")%></td>
            <td><%= @Originator.firstname %> <%= @Originator.lastname %></td>
            <td><%= link_to '<i class="fa fa-mail-reply"></i>'.html_safe, conversation_path(conversation), {:'data-toogle' => 'tooltip', :title => 'Antworten', :class => 'text-weak'}%></td>
            <td><%= link_to '<i class="fa fa-undo"></i>'.html_safe, conversation_untrash_path(conversation), :method => :post, :'data-toogle' => 'tooltip', :title => 'In den Posteingang verschieben', :class => 'text-weak'%></td>
            <td><%= link_to '<i class="fa fa-trash-o text-danger"></i>'.html_safe, conversation_delete_path(conversation), :method => :delete, :confirm=>'Möchten Sie die Konversation wirklich entgütig löschen?', :'data-toogle' => 'tooltip', :title => 'Entgültig löschen'%></td>
          </tr>
          
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/conversations/index.html.erb
<div id="page-wrapper">
    <div class="row">
      <div class="col-lg-12">
       <h1>Nachrichten <small><%= current_user.firstname %> <%= current_user.lastname %></small></h1>
        <ol class="breadcrumb">
          <li><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
         <li><i class="fa fa-envelope"></i> Nachrichten</li>
        </ol>
      </div>
    </div><!-- /.row -->
   <%= render @partial %>
  </div>

app/views/conversations/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Nachrichten <small>Neue Konversation</small></h1>
      <ol class="breadcrumb">
        <li><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
        <li><%= link_to '<i class="fa fa-envelope"></i> Nachrichten'.html_safe , conversations_path %></li>
        <li><i class="fa fa-comments"></i> Neue Konversation</li>
      </ol>
    </div>
  </div><!-- /.row -->
</div>

<div class="border-form-div">
  <%= form_for :conversation, url: :conversations do |f| %>
  <div class="form-group">
	<div class="input-group">
		<span class="input-group-addon">@</span>
		<%= f.email_field :recipients, :autofocus => true, :class=>'form-control', :placeholder => 'E-Mail' %>
	</div>
  </div>
  <div class="form-group">
	<div class="input-group">
    <span class="input-group-addon"><i class="fa fa-quote-left"></i></span>
		<%= f.text_field :subject, :class=>'form-control', :placeholder => 'Konversationsthema' %>
	</div>
  </div>
  <div class="form-group">
	<div class="input-group">
    <span class="input-group-addon"><i class="fa fa-comment"></i></span>
		<%= f.text_area :body, :class=>'form-control', :placeholder => 'Nachricht' %>
	</div>
  </div>
  <div class="form-group">
	<%= f.submit "Absenden", :class=>'btn btn-primary'%>
  </div>
  <% end %>
</div>

app/views/conversations/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1><%= conversation.subject %> <small>Nachrichten</small></h1>
      <ol class="breadcrumb">
        <li><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
        <li><%= link_to '<i class="fa fa-envelope"></i> Nachrichten'.html_safe , conversations_path %></li>
        <li><i class="fa fa-comments"></i> <%= conversation.subject %></li>
      </ol>
    </div>
  </div><!-- /.row -->
  
  <div class="row">
    <div class="col-lg-2">
      <div class="list-group"> 
        <%= link_to '<i class="fa fa-trash-o"></i> In den Papierkorb'.html_safe, conversation_trash_path(conversation), :method => :post, :id => conversation.id, :class => 'list-group-item' %>
        <%= link_to '<i class="fa fa-envelope"></i> Als ungelesen markieren'.html_safe, conversation_mark_as_unread_path(conversation),  :method => :post, :id => conversation.id, :class => 'list-group-item' %>
      </div>
    </div>
    <div class="col-lg-10">
      <div class="row"><!-- row Reply-->
        <div class="col-lg-1">
          <div class="pull-right">
          <%= image_tag avatar_url(current_user, 90) %>
          </div>
        </div>
        <div class="col-lg-11">
          
          <div class="panel panel-default">
            <div class="panel-heading">
               <span class="panel-title"><%= current_user.firstname %> <%= current_user.lastname%></span>
            </div>
            <div class="panel-body">

             <%#= link_to 'test', conversation_reply_path(conversation), :method => :post %>
			 <%= form_tag conversation_reply_path(conversation) do %>
			 <%= text_field_tag 'body' %>
			 <%= submit_tag "absenden" %>
             <%end%>
                         </div>
          </div><!-- /.Panel -->
        </div>
      </div><!-- /.row Reply-->
      <% conversation.receipts_for(current_user).order('updated_at DESC').each do |receipt| %>
      <div class="row">
        
          <% message = receipt.message%>
          <% conversation.mark_as_read(current_user) %>
         <% @sender = User.where(email: message.sender.email).first %>
        <div class="col-sm-1">
          <div class="pull-right">
          <%= image_tag avatar_url(@sender, 90) %>
          </div>
        </div>
        <div class="col-sm-11">
          
          <div class="panel panel-default">
            <div class="panel-heading">
               <span class="panel-title"><%= @sender.firstname %> <%= @sender.lastname%></span>
            </div>
            <div class="panel-body">
              <%= message.body %>
            </div>
          </div><!-- /.Panel -->
        </div>
     </div><!-- /.row -->
    <% end %>
    </div>
  </div><!-- /.row -->
  
  



</div><!-- /.page-wrapper -->