config/routes.rb
Komana::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :projects
  get "welcome/index"
  
  
  root "welcome#index"
  get "welcome/dashboard"
  get "portfolios/contact"
  

  resources :portfolios
 
  resources :conversations do
	post :reply
	post :trash
	post :untrash
    post :mark_as_unread
    post :mark_as_read
    delete :delete
  end
  
  #needed for the dashboard overview
  resources :tasks do
    collection do
	    get "search"
    end
	post :update_position
  end
  
  resources :lists do
		post "move_up"
		post "move_down"
  end
  

  resources :projects do
		post "add_user"
		post "remove_user"
	resources :lists do
		resources :tasks
	end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :authenticate_user!, except: [:index]

	def index
		if signed_in? 
			redirect_to welcome_dashboard_path
		end
	end	
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/dashboard.html.erb
<div id="page-wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h1>Dashboard <small><%= current_user.firstname %> <%= current_user.lastname %></small></h1>
            <ol class="breadcrumb">
              <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
            </ol>
          </div>
        </div><!-- /.row -->

        <div class="row">
          <div class="col-lg-3">
            <div class="panel panel-info">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-clipboard fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">
                      <%= Project.get_my_projects(current_user.id).count %>
                    </p>
                    <p class="announcement-text">Aktuelle Projekte</p>
                  </div>
                </div>
              </div>
              <%= link_to (projects_path) do%>
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                      Projekte<br> anzeigen
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="panel panel-warning">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-edit fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading"><%= Task.get_my_tasks(current_user.id).count %></p>
                    <p class="announcement-text">Aufgaben warten</p>
                  </div>
                </div>
              </div>


			  <%= link_to search_tasks_path do%>

                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                    Aufgaben<br>anzeigen
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="panel panel-danger">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-exclamation fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                    <p class="announcement-heading">
                      <%= Task.get_urgent_tasks_count(current_user.id) %>
                    </p>
                    <p class="announcement-text">
						Wichtige Aufgaben
					</p>
                  </div>
                </div>
              </div>
              <%= link_to search_tasks_path(:partial => 'tasks/urgent_tasks') do%>
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                      Aufgaben anzeigen
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="panel panel-success">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-6">
                    <i class="fa fa-tasks fa-5x"></i>
                  </div>
                  <div class="col-xs-6 text-right">
                  <p class="announcement-heading">       
                    <%= Task.get_free_tasks(current_user.id) %></p>
                  <p class="announcement-text">Freie Aufgaben</p>
                  </div>
                </div>
              </div>
              <%= link_to search_tasks_path( :partial => 'tasks/free_tasks') do %>
                <div class="panel-footer announcement-bottom">
                  <div class="row">
                    <div class="col-xs-6">
                    Aufgaben Anzeigen
                    </div>
                    <div class="col-xs-6 text-right">
                      <i class="fa fa-arrow-circle-right"></i>
                    </div>
                  </div>
                </div>
             <% end %>
            </div>
          </div>
        </div><!-- /.row -->

      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->
    

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Koala Management!</h1>
    <p>Sie verbringen mehr Zeit damit ihr Team im Griff zu halten als mit der Arbeit selbst?</p>
    <p>Dann sollten Sie uns kennenlernen!</p
   <p>
    <%= link_to 'Jetzt registrieren!', new_user_registration_path, :class => "btn btn-primary btn-lg"%>
   </p>
  </div>
</div>