config/routes.rb
Komana::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :projects
  get "welcome/index"
  
  
  root "welcome#index"
  get "welcome/dashboard"
  get "portfolios/contact"
  

  resources :portfolios
 
  resources :conversations do
	post :reply
	post :trash
	post :untrash
    post :mark_as_unread
    post :mark_as_read
    delete :delete
  end
  
  #needed for the dashboard overview
  resources :tasks do
    collection do
	    get "search"
    end
	post :update_position
  end
  
  resources :lists do
		post "move_up"
		post "move_down"
  end
  

  resources :projects do
		post "add_user"
		post "remove_user"
	resources :lists do
		resources :tasks
	end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :lists, :dependent => :destroy
	has_and_belongs_to_many :users

	validates :name, presence: true, length: { minimum: 3 }
	
	
	def self.get_my_projects(user_id)
		my_projects = Project.joins(:users).where("user_id = ?", user_id)
		return my_projects
	end
	
	
	def get_last_updated

	 	@project = Project.find(id)
	 	last_updated_list = List.where("project_id = ?", id).order(:updated_at).first
	 	last_updated_lists_for_tasks = List.where("project_id = ?", id)

		 	last_updated_lists_for_tasks.each do |last_updated|

				 		last_updated_task = last_updated.tasks.order(:updated_at).first

				if last_updated_task.nil?
				
					elsif last_updated_task.updated_at >= last_updated_list.updated_at && last_updated_task.updated_at > @project.updated_at
					 	@project.updated_at = last_updated_task.updated_at
					end
				if last_updated_list.updated_at > @project.updated_at
				 		@project.updated_at = last_updated_list.updated_at
				end
			end
		return @project.updated_at
	end
	
end

app/controllers/models/project.rb
class Project < ActiveRecord::Base
	has_many :lists, :order => "position ASC"
end

app/controllers/projects_controller.rb
# coding: UTF-8
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_auth, :only => [:destroy, :add_user]

 

  	def check_auth
  		@project = Project.find(params[:project_id])
 		project_user = ProjectsUsers.where("user_id =? and project_id=?", current_user, @project.id).first

  		if project_user.role != "author"
  			flash[:error] = "Für diesen Vorgang haben Sie keine Berechtigung."
  			redirect_to project_path(@project)
  		end
  	end

	def new 
		@project = Project.new
	end
	
	def create
		
		@project = Project.new(project_params)

			if @project.save	
				ProjectsUsers.addUserToProject(@project.id, current_user.id, "author")

				redirect_to project_path(@project)

		  	else 
			  	render new_project_path
  			end 
	end
	
	
	def add_user
		@project = Project.find(params[:project_id])
		@user = User.where("email = ?", params[:user_email]).first
		
		if @user.present? && @project.present?

			ProjectsUsers.addUserToProject(@project.id, @user.id, "member") 
			@user.notify("#{current_user.firstname} #{current_user.lastname} added you to Project \"#{@project.name}\"." , "added to Project" ).conversation
			redirect_to project_path(@project)
		else
			redirect_to project_path(@project)
			flash[:error] = "Dieser Benutzer existiert nicht, bitte prüfen sie ihre Eingabe"
		end
	end 

	def remove_user
		project = Project.find(params[:project_id])
		user = current_user

		if user.present?
			user.notify("Sie haben Project \"#{project.name}\" verlassen." , "left the Project" ).conversation
			ProjectsUsers.removeUserFromProject(project.id, user.id)
			redirect_to projects_path
		else
			redirect_to project_path(project)
			flash[:error] = "Ein Fehler ist aufgetreten, bitte versuchen sie es erneut"
		end
	end
	
	def show
		@project = Project.find(params[:id])
		#used for the task modal.
		@current_task = Task.new
		@lists = List.where("project_id = ?",  @project.id).order("position ASC")

	end
	
	def index
		@projects = Project.all
	end
	
	def destroy 
	   @project = Project.find(params[:project_id])
	   @project.destroy
	   
	   redirect_to projects_path
	end
	
	
private
	def project_params
		params.require(:project).permit(:name)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def get_title_class(assigned_user)
    if assigned_user.present?
      return "task-title"
    else
      return "task-title-small"
    end
  end
end

app/views/projects/_settings_modal.html.erb
<!-- Settingsmodal --> 
<div class="modal fade" id="settingsModal" tabindex="-1" role="dialog" aria-labelledby="settingsModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="settingsModalLabel">Projekteinstellungen</h4>
			</div>
			
			<div class="modal-body">
        <label>Projektteilnehmer</label><br>
				<!-- Display long batches of the users who are added the current in the project -->
				<% @project.users.each_with_index do |user| %>     
					<div class="user-batch">
						<%= image_tag avatar_url(user, 30), :class => "user-image" %>
						<div class="user-name">
							<%= user.firstname %> <%= user.lastname %>
						</div>
					</div>
				<% end %><%# /User batch %>
			
				<!-- add a new user to the project -->
				<% @user = ProjectsUsers.where("user_id =? and project_id=?", current_user, @project.id).first %>
				<% if @user.role == "author" %>
					<%= form_tag project_add_user_path(@project.id) do %>
					<div class="form-group">
						<label for="exampleInputEmail1">Benutzer hinzufügen</label>
						<%= text_field_tag :user_email, nil, :class => "form-control", :placeholder => 'E-Mail' %>
						</div>

					<%= submit_tag "Hinzufügen", :class=>'btn btn-primary' if @user.role == "author"%>
					
				  <% end %>
				<% end %><%# IF User is author%>
        
        <hr>

				<!-- leave current Project -->
        <% if @user.role != "author" %>
				<%= form_tag project_remove_user_path(@project.id) do  %>
        <div class="form-group">
					<%= submit_tag "Projekt verlassen", :class=>'btn btn-danger'%>
					</div>
				<% end %><%# /leave current project form%>
        <% else %>
        <form role="form">
          <div class="form-group">
            <%= link_to 'Projekt löschen', project_path(:project_id => @project), method: :delete, :confirm => "Soll das Projekt wirklich gelöscht werden?", :class => 'btn btn-danger' %>
          </div>
        </div>
        <% end %><%# /leave current project%>

        
      </div>


			
		</div><!--/.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/projects/_task_modal.html.erb
 
<!-- Task-Modal --> 

<div class="modal fade" id="editTaskModal" tabindex="-1" role="dialog" aria-labelledby="editTaskModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		
		<div class="modal-content">
			<%= form_tag project_list_task_path(@project.id, 0, 0), :method => :put, :html => {:class => 'form-inline'} do %>
			<%= hidden_field_tag 'task_id', NIL, {:class => 'form-control'} %>
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="editTaskModalLabel"><%= text_field_tag :titel, NIL, {:class => 'form-control', :id=> 'task_titel'} %></h4>
			</div>
		
			<div class="modal-body">
				<h4>Zuweisen an: </h4><%= select_tag "user_id", options_from_collection_for_select(@project.users, "id", "firstname"), include_blank: true, :class => "form-control" %>
				<%# form for priority %> 
				
				<h4>Priorität: </h4>
        <p>
				<%= radio_button_tag(:priority, "low") %>
				<%= label_tag(:priority_low, "Niedrig") %>
				<%= radio_button_tag(:priority, "medium") %>
				<%= label_tag(:priority_medium, "Mittel") %>
				<%= radio_button_tag(:priority, "high") %>
				<%= label_tag(:priority_high, "Hoch") %>
        </p>
      
      <%# for for deadline %> <h4>Frist: </h4>
        <div class="input-group date">
				  <%= text_field_tag(:deadline, nil, class: 'form-control') %><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
        </div>
				
				<div class="form-group"> 
					<h4>Beschreibung:</h4>
					<%= text_area_tag :text, NIL, {:size => "100x7", :class => 'form-control', :id=> 'task_text'} %>
				</div>
			</div>
			
			<div class="modal-footer">
				<%= submit_tag "Speichern", :class => 'btn btn-primary' %>
				<% end %>        
				<button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
			</div>
		</div><!--/.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/projects/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1>Meine Projekte <small>Übersicht</small></h1>
      <ol class="breadcrumb">
        <li><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
        <li class="active"><i class="fa fa-clipboard"></i> Meine Projekte</li>
      </ol>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-hover"> 
     
     <% @projects = Project.joins(:users).where("user_id = ?", current_user.id) %>
      <tr>
        <th>Projekt</th>
        <th>Projektleiter</th>
        <th>Erstellt am</th>
        <th>Letzte Änderung am</th>
      </tr>
      <% @projects.each do |project| %>

      <% @project_owner = ProjectsUsers.where(:role => 'author', :project_id => project.id).first %>

      <% @project_user = User.where("id = ?", @project_owner.user_id).first if @project_owner.present?%>
        <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <% if @project_owner.present? %>
        <td><%= @project_user.firstname %> <%= @project_user.lastname %> </td>
        <% else %>
        <td> Gelöschter Nutzer </td>
        <% end %>
        <td><%= project.created_at.strftime("%d.%m.%Y") %></td>
        <td><%= project.get_last_updated.strftime("%d.%m.%Y") %></td>
      </tr>
     <% end %>
    </table>
    <%= link_to 'Neues Projekt erstellen', new_project_path, :class => 'btn btn-default' %>
  </div>
</div>

app/views/projects/new.html.erb
<div id="page-wrapper">
	<div class="row">
		<div class="col-lg-12">
			<h1>Meine Projekte <small>Neues Projekt anlegen</small></h1>
			<ol class="breadcrumb">
				<li><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
				<li><%= link_to '<i class="fa fa-clipboard"></i> Meine Projekte'.html_safe , projects_path %></li>
				<li class="active"><i class="fa fa-plus"></i> Neues Projekt anlegen</li>
			</ol>
		</div>
	</div>


	<!-- Form that will submit name to create action of projects controller  -->
	<%= form_for :project, url: projects_path, :role => 'form' do |f| %>

		<%= f.label "Projektname" %>
		<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-2">
		<%= f.text_field :name,:class=>'form-control', :placeholder => 'Projektname' %>
	  </div>
	</div>

	<%# validation handling %>
	<div class="validation-group  text-danger">
		 <% @project.errors.full_messages_for(:name).each do |msg| %>
		   <%= msg %>
		   <% break %> 
		 <% end %>
	</div>


	<br/ >
	<div class="row">
		<div class="col-xs-12 col-md-4 col-lg-2 ">
		<%= f.submit "Anlegen", :class=>'btn btn-primary'%> 

		<%= link_to 'Abbrechen', projects_path, :class => 'btn btn-default' %>
	  </div>
	</div>
			
	<% end %>
</div>

app/views/projects/show.html.erb
<div class=""id="page-wrapper">
<div class="row">
<div class="col-lg-12">
<h1><%= @project.name %> <small>Organisation</small></h1>

<ol class="breadcrumb">
<li><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
<li><%= link_to '<i class="fa fa-clipboard"></i> Meine Projekte'.html_safe , projects_path %></li>
<li class="active"><i class="fa fa-clipboard"></i> <%= @project.name %></li>
<span class="pull-right"><a class="text-weak" data-toggle="modal" data-target="#settingsModal"><i class="fa fa-gear"></i></a></span>
</ol><!-- /breadcrumb -->
      
</div><!-- /col-lg-12 -->
</div><!-- /row -->
</div><!--/page wrapper -->
<ul class="lists-ul">
<% @lists.each do |list| %>	<%# List loop %>
  <li class="lists-li">
    <div class="well well-lg lists-well">
      <!-- Lists navigations links -->
      <!-- TODO: replace with drag and drop -->
<%= link_to '<i class="fa fa-arrow-circle-left"></i>'.html_safe, list_move_down_path(:list_id => list), :method => :POST if list != @lists.first %>
<%= link_to '<i class="fa fa-arrow-circle-right"></i>'.html_safe, list_move_up_path(:list_id => list), :method => :POST if list != @lists.last %>
      
      <!-- list header, changes to input field for list name on click -->
<h4> <strong class="list-title" onClick = "updateList(this, <%= list.id%>);"><%= list.name %></strong>


        <!-- lists dropdown menu -->
<div class="dropdown pull-right">
<!-- settings for the list. Allows to add a new task and delete the whole list -->
        <button class="btn dropdown-toggle" type="button" data-toggle="dropdown"><span class="fa fa-bars"></span></button>
        <ul class="dropdown-menu" role="menu">
          <li role="presentation"><%= link_to 'Aufgabe anlegen', project_list_tasks_path(@project, list), :method =>:post %></li>
<li role="presentation" class="divider"></li>
<li role="presentation"><%= link_to 'Liste löschen <i class="fa fa-exclamation-circle"></i>'.html_safe, project_list_path(project_id:@project, list_id:list), method: :delete, :confirm => "Soll die Liste wirklich gelöscht werden?" %></li>
</ul>
</div><!-- /lists dropdown menu -->
      </h4><!-- list header -->
      
      <br/>
      
      <!-- Get all Tasks in the List and renders them-->
      <% ordered_tasks = list.tasks.order("position DESC") %>
<% ordered_tasks.each do |task| %><%# tasks loop %>
      
<!-- TODO: Dynamisch mit coffescript hinzufügen, vor alle tagged elemente -->
<!-- Drag & Drop target Div -->
<div class ="droptarget task<%= task.id %> position<%=task.position%> list<%= list.id %>" ondrop = "dropEvent(event, '<%= task.position %>', '<%= task.list.id %>');"></div>
      <!-- /Drag & Drop target div -->
      
      <!-- task -->
<div class="panel panel-default task<%= task.id %> position<%=task.position%> list<%= list.id %> draggable" draggable="true" ondragstart = "dragstartEvent(event, '<%= task.id %>', '<%= task.position %>', '<%= task.list.id %>');">
        <!-- task header -->
<div class="panel-heading">
          <%# Select and display the priority %>
          <% case task.priority
            when "low" %><div class="priority priority-low"></div>
            <% when "medium" %><div class="priority priority-medium"></div>
            <% when "high" %><div class="priority priority-high"></div>
            <% end %>
            <%# /priority select%>
            
            <%# Gets the to this task assigned user %>
<% assigned_user = task.users.first %>
            <!-- shows the to this task assigned user, if there is any -->
<% if assigned_user.present? %>
              <%# Needed to set the default value of the tasks modal %>
<% assigned_user_id = assigned_user.id %>
              <!-- renders the user short batch with initials and his avatar -->
<div class="user-batch batch-task">
<%= image_tag avatar_url(assigned_user, 30), :class => "user-image" %>
<div class="user-name">
<%= assigned_user.firstname.first %><%= assigned_user.lastname.first %>
</div><!-- /user initials -->
</div><!-- /user batch -->
            <% else %>
              <% assigned_user_id = NIL %>
            <% end %>
            
            <!-- Task title -->
            <div class="<%= get_title_class(assigned_user) %>">
              <!-- opens the task modal on click to edit its values. Changes will be saved with Ajax call. -->

			  <a class ="task_modal" onClick = "updateTask(<%= task.id %>, '<%= task.titel %>','<%= task.text %>', '<%= assigned_user_id %>', '<%= task.priority %>', '<%= task.deadline %>' );">
			    <strong>
                  <%= task.titel %>
				</strong>
				
			  </a><!-- /Link to task edit modal -->
              <!-- button to delete the task. Opens confirmation window before -->
				  <%= link_to '&times;'.html_safe, project_list_task_path(project_id:@project, list_id:list, task_id:task), method: :delete, :class => "close", :confirm => "Soll die Aufgabe wirklich gelöscht werden?" %>

            </div><!-- /Task title -->
        </div><!-- /task header -->
        
        <!-- Task description body -->
        <div class="panel-body">
          <!-- Task description -->
          <%= task.text %>
          <br>
          <br>
          <%# Show deadline if it is set %>
          <% if task.deadline.present? %>
          <!-- task footer in the body that displays the remaining time for a task -->
<small class="text-weak">
            <!-- clock symbol -->
<i class="fa fa-clock-o"></i>
            Endet in <%= distance_of_time_in_words(Time.now.utc.localtime, task.deadline.to_datetime) %>
          </small><!-- /Task footer -->
          <% end %>
        </div><!-- /Task description body -->
      </div><!-- /task -->
      <% end %> <%# /task loop%>
      <!-- Default Drag & Drop target Div -->
      <div class ="droptarget position0 list<%= list.id %>" ondrop = "dropEvent(event, 0, '<%= list.id %>');"></div>
    </div><!-- /lists-well -->
  </li>
  <% end %><%# /List loop %>
  
  <!-- Add an additional List on click -->
  <li class="lists-li">
<div class="well well-lg">
<h4><strong><%= link_to 'Neue Liste anlegen...', project_lists_path(@project), :method => :POST %></strong></h4>
</div>
  </li><!-- add list button -->
</ul><!-- /lists-ul -->

<!-- modal partials -->
<%= render 'task_modal' %>
<%= render 'settings_modal' %>