config/routes.rb
Komana::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :projects
  get "welcome/index"
  
  
  root "welcome#index"
  get "welcome/dashboard"
  get "portfolios/contact"
  

  resources :portfolios
 
  resources :conversations do
	post :reply
	post :trash
	post :untrash
    post :mark_as_unread
    post :mark_as_read
    delete :delete
  end
  
  #needed for the dashboard overview
  resources :tasks do
    collection do
	    get "search"
    end
	post :update_position
  end
  
  resources :lists do
		post "move_up"
		post "move_down"
  end
  

  resources :projects do
		post "add_user"
		post "remove_user"
	resources :lists do
		resources :tasks
	end
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<div id="wrapper">
<!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to '<i class="fa fa-puzzle-piece"></i> Koala Management'.html_safe , root_path, :class => 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in?%>
            <li class="<%= "active" if params[:controller] == "welcome" %>"><%= link_to '<i class="fa fa-dashboard"></i> Dashboard'.html_safe , root_path %></li>
            <li class="<%= "active" if params[:controller] == "projects" %>"><%= link_to '<i class="fa fa-clipboard"></i> Projekte'.html_safe , projects_path %></li>
            <% else %>
            <li class="<%= "active" if params[:controller] == "welcome" %>"><%= link_to '<i class="fa fa-home"></i> Start'.html_safe , root_path %></li>
            <% end %>
            <li class="dropdown alerts-dropdown <%= "active" if params[:controller] == "portfolios" %>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-info"></i> Über uns <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to '<i class="fa fa-users"></i> Das Team'.html_safe , portfolios_path %></li>
                <li><%= link_to '<i class="fa fa-phone"></i> Kontakt'.html_safe , portfolios_contact_path %></li>
              </ul>
            </li>
            
          </ul>

          <ul class="nav navbar-nav navbar-right navbar-user">
          <% if user_signed_in? %>
            <li class="dropdown messages-dropdown <%= "active" if params[:controller] == "conversations" %>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Nachrichten <span class="badge"><%= current_user.mailbox.inbox(:read => false).count(:id, :distinct => true).to_s %></span> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header"><%= current_user.mailbox.inbox(:read => false).count(:id, :distinct => true).to_s %> Neue Nachrichten</li>
                <% current_user.mailbox.inbox(:read => false).order('updated_at ASC').each_with_index do |conversation, n| %>
                <% if (n<3)%>
                <% if conversation.last_sender.present? %>
                <% @last_sender = User.where(email: conversation.last_sender.email).first%>
                <% else %>
                <% @last_sender = create_temp_deleted_user() %>
                <% end %>
                <li class="message-preview">
                <%= link_to conversation_path(conversation), :method => :get do %>
                    <span class="avatar"><%= image_tag avatar_url(@last_sender, 50), :size => "50" %></span>
                    <span class="name"><%= @last_sender.firstname %> <%= @last_sender.lastname%></span>
                    <span class="message"><%=raw truncate(conversation.last_message.body, :length => 40,  :omission => "...") %></span>
                    <span class="time"><i class="fa fa-clock-o"></i> vor <%= time_ago_in_words(conversation.created_at) %></span>
                  <% end %>
                </li>
                <li class="divider"></li>
                <% end %>
                <% end %>
                <li><%= link_to "Posteingang öffnen", conversations_path  %></li>
              </ul>
            </li>
            <% end %>
            
            
            <% if current_user %>
            <li class="dropdown user-dropdown <%= "active" if params[:controller] == "devise/registrations" %>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= " #{current_user.firstname}  #{current_user.lastname} " %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to '<i class="fa fa-user"></i> Profil'.html_safe , edit_user_registration_path %></li>
                <li><%= link_to '<i class="fa fa-envelope"></i> Posteingang <span class="badge">'.html_safe + current_user.mailbox.inbox(:read => false).count(:id, :distinct => true).to_s + '</span>'.html_safe, conversations_path  %>
                <!-- <li><a href="#"><i class="fa fa-gear"></i> Einstellungen</a></li> -->
                <li class="divider"></li>
                <li><%= link_to '<i class="fa fa-power-off"></i> Abmelden'.html_safe, destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
            <% else %>
            <li class="<%= "active" if params[:controller] == "devise/sessions" %>"><%= link_to '<i class="fa fa-sign-in"></i> Anmelden '.html_safe, new_user_session_path %> </li>
            <li class="<%= "active" if params[:controller] == "devise/registrations" %>"><%= link_to '<i class="fa fa-pencil"></i> Registrieren '.html_safe, new_user_registration_path %></li>
            <% end %>
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
    </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Komana" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Komana" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
    </header>
       <%= yield %>

  </body>
</html>